import Header from "@/components/about/Header";
import MainAbout from "@/components/about/MainAbout";
import Cta from "@/components/navigation/cta";
import Footer from "@/components/navigation/footer";
import Navbar from "@/components/navigation/navbar";
import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About | PT. BERLIAN ANUGERAH TRANSPORTASI",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <>
      <Navbar />
      <main className="bg-slate-50">
        <Header />
        <MainAbout />
      </main>
      <Cta />
      <Footer />
    </>
  );
}
