import Header from "@/components/home/Header";
import Image from "next/image";
import type { Metadata } from "next";
import Services from "@/components/home/Services";
import WhyChooseUs from "@/components/home/WhyChooseUs";
import Faq from "@/components/home/Faq";

export const metadata: Metadata = {
  title: "Home | PT. BERLIAN ANUGERAH TRANSPORTASI",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="bg-slate-50">
      <Header />
      <Services />
      <WhyChooseUs />
      <Faq />
    </main>
  );
}
